tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: site_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Site name'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: phone
            field:
              input_type: tel
              antlers: false
              type: text
              display: Phone
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: email
            field:
              input_type: email
              antlers: false
              type: text
              display: Email
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: address
            field:
              input_type: text
              antlers: false
              display: Address
              type: text
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: zip
            field:
              input_type: text
              antlers: false
              display: Zip
              type: text
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: cvr
            field:
              input_type: text
              antlers: false
              display: Cvr
              type: text
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            import: socialmedia_links
          -
            handle: opening_hours
            field:
              display: 'Opening hours'
              type: list
              icon: list
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: contact_thanks_page_redirect
            field:
              collections:
                - pages
              type: link
              display: 'Contact thanks page redirect'
              icon: link
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
